[project]
name = "loclass-starter"
version = "0.3.1"
description = "Backend agnostic document framework"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "loclass",
    "loclass-ldl",
]

[dependency-groups]
dev = [
    "ruff",
    "mypy",
]

[tool.hatch.build.targets.wheel]
packages = ["core"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.loclass.dev]
tex_main = "main.tex"
build_dir = "build"
typecheck = ["core"]
lint = ["."]

[tool.uv.sources]
loclass = { path = "../loclass-base", editable = true }
loclass-ldl = { path = "../loclass-ldl", editable = true }
