[project]
name = "loclass"
version = "0.1.0"
description = "Backend agnostic document framework"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[project.scripts]
loclass-render = "core.tools.ldl_renderer:main"

[dependency-groups]
dev = [
    "pytest>=9.0",
]

[tool.pytest.ini_options]
testpaths = [
    "core/tests",
]
pythonpath = [
    ".",
]
python_files = [
    "test_*.py",
]

[tool.hatch.build.targets.wheel]
packages = ["core"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
